<h2>Статьи</h2>
<a href="/admin/article/add/">Добавить</a><br><br>
<?php
    $flash = $this->flashMesseger();
    $flash->setMessageOpenFormat('<div%s <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                                    &times; </button><ul><li>')
                                    ->setMessageSeparatorString('</li><li>')
                                    ->setMessageCloseString('</li></ul></div>');

    echo $flash->render('error', array('alert', 'alert-dismissable', 'alert-danger'));
    echo $flash->render('error', array('alert', 'alert-dismissable', 'alert-info'));
    echo $flash->render('error', array('alert', 'alert-dismissable', 'alert-warning'));
    echo $flash->render('error', array('alert', 'alert-dismissable', 'alert-success'));


?>